on:
  push:
    branches: [ "main" ]  # Ejecuta este flujo de trabajo cuando haya un push en la rama main
  workflow_dispatch:  # También puedes ejecutarlo manualmente desde GitHub Actions UI

env:
  AZURE_WEBAPP_NAME: Finnovate     # Nombre de la aplicación web en Azure
  AZURE_WEBAPP_PACKAGE_PATH: '.'  # Ruta a tu proyecto de Node.js (por defecto la raíz del repo)
  NODE_VERSION: '20.x'           # Versión de Node.js a usar

permissions:
  contents: read  # Permiso de lectura para acceder al contenido del repositorio

jobs:
  build:
    runs-on: ubuntu-latest  # Este trabajo se ejecuta en una máquina con Ubuntu

    steps:
    - uses: actions/checkout@v4  # Clona tu repositorio

    - name: Set up Node.js
      uses: actions/setup-node@v4  # Configura Node.js
      with:
        node-version: ${{ env.NODE_VERSION }}  # Usa la versión definida de Node
        cache: 'npm'  # Activa la caché para npm

    - name: npm install, build, and test
      run: |
        npm install        # Instala dependencias
        npm run build --if-present  # Si existe el script "build", lo ejecuta
        npm run test --if-present   # Si existe el script "test", lo ejecuta

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3  # Sube los archivos del build para ser usados en el trabajo de despliegue
      with:
        name: node-app
        path: .  # Sube toda la raíz del proyecto

  deploy:
    permissions:
      contents: none  # No se requieren permisos de contenido para este trabajo
    runs-on: ubuntu-latest
    needs: build  # Este trabajo depende del trabajo "build"

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3  # Descarga el artefacto del trabajo de build
      with:
        name: node-app

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2  # Usa la acción oficial de Azure para desplegar
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}  # Nombre de la aplicación web en Azure
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Secreto con el perfil de publicación
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}  # Ruta del paquete a desplegar
